### ISSUE TITLE
Can't Install from git url using poetry

### ISSUE THREAD

**Issue by haleemur** [1Password/connect-sdk-python#17]
### Your environment

SDK Version: 1.0.1

Connect Server Version: not-applicable

OS: ubuntul 20.04

Python Version: 3.8

## What happened?
poetry can't install this library from a git url. i get the following error.

```
Updating dependencies
Resolving dependencies... (0.4s)
  CalledProcessError
  Command '['git', '--git-dir', '/tmp/pypoetry-git-connect-sdk-python4l7tbflx/.git', '--work-tree', '/tmp/pypoetry-git-connect-sdk-python4l7tbflx', 'checkout', 'master']' returned non-zero exit status 1.
  at ~/.poetry/lib/poetry/utils/_compat.py:217 in run
      213│                 process.wait()
      214│                 raise
      215│             retcode = process.poll()
      216│             if check and retcode:
    → 217│                 raise CalledProcessError(
      218│                     retcode, process.args, output=stdout, stderr=stderr
      219│                 )
      220│         finally:
      221│             # None because our context manager __exit__ does not use them.
```
## What did you expect to happen?
i expected it to work

## Steps to reproduce
```python
poetry add git+https://github.com/1Password/connect-sdk-python.git
```

**Comment by SimonBarendse** [comment]
The default branch of this repository is `main` and it seems like the version of Poetry you have installed assumes we're using `master`. I believe this upstream issue tackles the problem https://github.com/python-poetry/poetry/issues/3366 .

I'll close the issue here in favor of the upstream issue. Please feel free to re-open if you believe there's something we should change.
